-- +goose Up
-- create "additional_migrates" table
CREATE TABLE "additional_migrates" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "version" bigint NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "additional_migrates_name_key" to table: "additional_migrates"
CREATE UNIQUE INDEX "additional_migrates_name_key" ON "additional_migrates" ("name");
-- create "chat_histories" table
CREATE TABLE "chat_histories" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "request_message" character varying NOT NULL,
  "reply_message" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "chatroom_chat_histories" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- create "chat_history_details" table
CREATE TABLE "chat_history_details" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "model" character varying NOT NULL,
  "full_request_message" jsonb NOT NULL,
  "request" jsonb NOT NULL,
  "response" jsonb NOT NULL,
  "prompt_price" numeric NOT NULL,
  "completion_price" numeric NOT NULL,
  "chat_history_detail" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- create "chatroom_rag_reference_pool" table
CREATE TABLE "chatroom_rag_reference_pool" (
  "chatroom_id" bigint NOT NULL,
  "rag_reference_pool_id" bigint NOT NULL,
  PRIMARY KEY ("chatroom_id", "rag_reference_pool_id")
);
-- create "chatrooms" table
CREATE TABLE "chatrooms" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "discord_guild_chatrooms" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- create "discord_commands" table
CREATE TABLE "discord_commands" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "discord_id" character varying NOT NULL,
  "sha256_checksum" bytea NOT NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "discord_commands_discord_id_key" to table: "discord_commands"
CREATE UNIQUE INDEX "discord_commands_discord_id_key" ON "discord_commands" ("discord_id");
-- create index "discord_commands_name_key" to table: "discord_commands"
CREATE UNIQUE INDEX "discord_commands_name_key" ON "discord_commands" ("name");
-- create "discord_guilds" table
CREATE TABLE "discord_guilds" (
  "id" character varying NOT NULL,
  "discord_guild_activate_chatroom" bigint NULL,
  PRIMARY KEY ("id")
);
-- create "discord_users" table
CREATE TABLE "discord_users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "discord_id" character varying NOT NULL,
  "guild_id" character varying NOT NULL,
  "name" character varying NOT NULL,
  "avatar_url" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "discorduser_discord_id_guild_id" to table: "discord_users"
CREATE UNIQUE INDEX "discorduser_discord_id_guild_id" ON "discord_users" ("discord_id", "guild_id");
-- create "images" table
CREATE TABLE "images" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "save_type" bigint NOT NULL,
  "save_path" character varying NOT NULL,
  "sha256_checksum" bytea NOT NULL,
  "created_at" timestamptz NOT NULL,
  "sticker_images" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- create "rag_reference_pools" table
CREATE TABLE "rag_reference_pools" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "description" character varying NOT NULL,
  "created_at" timestamptz NOT NULL,
  "discord_guild_rag_reference_pool" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- create "rag_reference_texts" table
CREATE TABLE "rag_reference_texts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "text" character varying NOT NULL,
  "embed_content" bytea NOT NULL,
  "embed_metadata" jsonb NOT NULL,
  "created_at" timestamptz NOT NULL,
  "rag_reference_pool_texts" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- create "stickers" table
CREATE TABLE "stickers" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "name" character varying NOT NULL,
  "discord_guild_sticker" character varying NOT NULL,
  PRIMARY KEY ("id")
);
-- create index "sticker_name" to table: "stickers"
CREATE UNIQUE INDEX "sticker_name" ON "stickers" ("name");
-- create "web_login_sessions" table
CREATE TABLE "web_login_sessions" (
  "id" uuid NOT NULL,
  "discord_user_web_login_session" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- modify "chat_histories" table
ALTER TABLE "chat_histories" ADD
 CONSTRAINT "chat_histories_chatrooms_chat_histories" FOREIGN KEY ("chatroom_chat_histories") REFERENCES "chatrooms" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "chat_history_details" table
ALTER TABLE "chat_history_details" ADD
 CONSTRAINT "chat_history_details_chat_histories_detail" FOREIGN KEY ("chat_history_detail") REFERENCES "chat_histories" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- modify "chatroom_rag_reference_pool" table
ALTER TABLE "chatroom_rag_reference_pool" ADD
 CONSTRAINT "chatroom_rag_reference_pool_chatroom_id" FOREIGN KEY ("chatroom_id") REFERENCES "chatrooms" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, ADD
 CONSTRAINT "chatroom_rag_reference_pool_rag_reference_pool_id" FOREIGN KEY ("rag_reference_pool_id") REFERENCES "rag_reference_pools" ("id") ON UPDATE NO ACTION ON DELETE CASCADE;
-- modify "chatrooms" table
ALTER TABLE "chatrooms" ADD
 CONSTRAINT "chatrooms_discord_guilds_chatrooms" FOREIGN KEY ("discord_guild_chatrooms") REFERENCES "discord_guilds" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "discord_guilds" table
ALTER TABLE "discord_guilds" ADD
 CONSTRAINT "discord_guilds_chatrooms_activate_chatroom" FOREIGN KEY ("discord_guild_activate_chatroom") REFERENCES "chatrooms" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- modify "images" table
ALTER TABLE "images" ADD
 CONSTRAINT "images_stickers_images" FOREIGN KEY ("sticker_images") REFERENCES "stickers" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "rag_reference_pools" table
ALTER TABLE "rag_reference_pools" ADD
 CONSTRAINT "rag_reference_pools_discord_guilds_rag_reference_pool" FOREIGN KEY ("discord_guild_rag_reference_pool") REFERENCES "discord_guilds" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "rag_reference_texts" table
ALTER TABLE "rag_reference_texts" ADD
 CONSTRAINT "rag_reference_texts_rag_reference_pools_texts" FOREIGN KEY ("rag_reference_pool_texts") REFERENCES "rag_reference_pools" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "stickers" table
ALTER TABLE "stickers" ADD
 CONSTRAINT "stickers_discord_guilds_sticker" FOREIGN KEY ("discord_guild_sticker") REFERENCES "discord_guilds" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- modify "web_login_sessions" table
ALTER TABLE "web_login_sessions" ADD
 CONSTRAINT "web_login_sessions_discord_users_web_login_session" FOREIGN KEY ("discord_user_web_login_session") REFERENCES "discord_users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;

-- +goose Down
-- reverse: modify "web_login_sessions" table
ALTER TABLE "web_login_sessions" DROP CONSTRAINT "web_login_sessions_discord_users_web_login_session";
-- reverse: modify "stickers" table
ALTER TABLE "stickers" DROP CONSTRAINT "stickers_discord_guilds_sticker";
-- reverse: modify "rag_reference_texts" table
ALTER TABLE "rag_reference_texts" DROP CONSTRAINT "rag_reference_texts_rag_reference_pools_texts";
-- reverse: modify "rag_reference_pools" table
ALTER TABLE "rag_reference_pools" DROP CONSTRAINT "rag_reference_pools_discord_guilds_rag_reference_pool";
-- reverse: modify "images" table
ALTER TABLE "images" DROP CONSTRAINT "images_stickers_images";
-- reverse: modify "discord_guilds" table
ALTER TABLE "discord_guilds" DROP CONSTRAINT "discord_guilds_chatrooms_activate_chatroom";
-- reverse: modify "chatrooms" table
ALTER TABLE "chatrooms" DROP CONSTRAINT "chatrooms_discord_guilds_chatrooms";
-- reverse: modify "chatroom_rag_reference_pool" table
ALTER TABLE "chatroom_rag_reference_pool" DROP CONSTRAINT "chatroom_rag_reference_pool_rag_reference_pool_id", DROP CONSTRAINT "chatroom_rag_reference_pool_chatroom_id";
-- reverse: modify "chat_history_details" table
ALTER TABLE "chat_history_details" DROP CONSTRAINT "chat_history_details_chat_histories_detail";
-- reverse: modify "chat_histories" table
ALTER TABLE "chat_histories" DROP CONSTRAINT "chat_histories_chatrooms_chat_histories";
-- reverse: create "web_login_sessions" table
DROP TABLE "web_login_sessions";
-- reverse: create index "sticker_name" to table: "stickers"
DROP INDEX "sticker_name";
-- reverse: create "stickers" table
DROP TABLE "stickers";
-- reverse: create "rag_reference_texts" table
DROP TABLE "rag_reference_texts";
-- reverse: create "rag_reference_pools" table
DROP TABLE "rag_reference_pools";
-- reverse: create "images" table
DROP TABLE "images";
-- reverse: create index "discorduser_discord_id_guild_id" to table: "discord_users"
DROP INDEX "discorduser_discord_id_guild_id";
-- reverse: create "discord_users" table
DROP TABLE "discord_users";
-- reverse: create "discord_guilds" table
DROP TABLE "discord_guilds";
-- reverse: create index "discord_commands_name_key" to table: "discord_commands"
DROP INDEX "discord_commands_name_key";
-- reverse: create index "discord_commands_discord_id_key" to table: "discord_commands"
DROP INDEX "discord_commands_discord_id_key";
-- reverse: create "discord_commands" table
DROP TABLE "discord_commands";
-- reverse: create "chatrooms" table
DROP TABLE "chatrooms";
-- reverse: create "chatroom_rag_reference_pool" table
DROP TABLE "chatroom_rag_reference_pool";
-- reverse: create "chat_history_details" table
DROP TABLE "chat_history_details";
-- reverse: create "chat_histories" table
DROP TABLE "chat_histories";
-- reverse: create index "additional_migrates_name_key" to table: "additional_migrates"
DROP INDEX "additional_migrates_name_key";
-- reverse: create "additional_migrates" table
DROP TABLE "additional_migrates";
