name: Go Backend CI

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci-backend.yml"
      - "backend/**"
      - "!**.md"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/ci-backend.yml"
      - "backend/**"
      - "!**.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"
          cache-dependency-path: |
            backend/go.sum

      - name: go generate
        working-directory: backend
        run: go generate ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.60.3
          # Optional: working directory, useful for monorepos
          working-directory: backend

      - name: Test
        working-directory: backend
        run: go test -v ./...

      - name: Build
        working-directory: backend
        run: CGO_ENABLED=0 go build -ldflags="-s"  -v ./...
